import Link from "next/link";

export default function TermsOfUsePage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <Link
        href="/meridial"
        className="mb-8 inline-block text-sm text-gray-500 transition-colors hover:text-gray-900"
      >
        &larr; Back
      </Link>

      <h1 className="mb-8 text-3xl font-bold text-gray-900">Terms of Use</h1>

      <div className="space-y-6 text-[15px] leading-relaxed text-gray-600">
        <p>
          <strong className="text-gray-900">Last updated:</strong> September 19, 2026
        </p>

        <h2 className="pt-2 text-xl font-semibold text-gray-900">
          1. Demo only
        </h2>
        <p>
          Meridial is a portfolio demo of document address extraction. It is provided
          as-is, without warranties, and is not a regulated KYC, credit, employment,
          or legal verification service.
        </p>

        <h2 className="pt-2 text-xl font-semibold text-gray-900">
          2. Acceptable use
        </h2>
        <p>
          Use the demo with sample or documents you are authorized to process. Do not
          attempt to abuse rate limits, probe other users&apos; data, or use outputs as
          the sole basis for consequential decisions about people.
        </p>

        <h2 className="pt-2 text-xl font-semibold text-gray-900">
          3. AI outputs
        </h2>
        <p>
          Extracted fields are generated by Google Gemini and may be incomplete or
          wrong. Always review source documents yourself before acting on any result.
        </p>

        <h2 className="pt-2 text-xl font-semibold text-gray-900">
          4. Availability and limits
        </h2>
        <p>
          The service may be rate-limited, changed, or taken offline at any time.
          PDFs may be truncated (for example to the first few pages) before analysis.
        </p>

        <h2 className="pt-2 text-xl font-semibold text-gray-900">
          5. Liability
        </h2>
        <p>
          To the fullest extent permitted by law, the operator is not liable for
          damages arising from use of this demo, including reliance on AI-extracted
          data.
        </p>

        <h2 className="pt-2 text-xl font-semibold text-gray-900">
          6. Contact
        </h2>
        <p>
          For questions, contact the site operator through{" "}
          <a
            href="https://joaog.space"
            className="underline hover:text-gray-900"
          >
            joaog.space
          </a>
          .
        </p>
      </div>
    </div>
  );
}
